// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWpj6yr2jexnJhkAYd3bIwPdbydqVOTU',
    appId: '1:26669208216:web:76946ae8ba6b069393b6ed',
    messagingSenderId: '26669208216',
    projectId: 'social-app-71c22',
    authDomain: 'social-app-71c22.firebaseapp.com',
    storageBucket: 'social-app-71c22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmizQL_F-fGbKt0o0PV60JnHPsIGZqBp0',
    appId: '1:26669208216:android:d344326eadd3c71493b6ed',
    messagingSenderId: '26669208216',
    projectId: 'social-app-71c22',
    storageBucket: 'social-app-71c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7wQhmMLaNkBiwuMFYZdiPnL3Wu5JCn8',
    appId: '1:26669208216:ios:7ebb6a0453a11a1593b6ed',
    messagingSenderId: '26669208216',
    projectId: 'social-app-71c22',
    storageBucket: 'social-app-71c22.appspot.com',
    iosBundleId: 'com.example.clinicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7wQhmMLaNkBiwuMFYZdiPnL3Wu5JCn8',
    appId: '1:26669208216:ios:7ebb6a0453a11a1593b6ed',
    messagingSenderId: '26669208216',
    projectId: 'social-app-71c22',
    storageBucket: 'social-app-71c22.appspot.com',
    iosBundleId: 'com.example.clinicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZWpj6yr2jexnJhkAYd3bIwPdbydqVOTU',
    appId: '1:26669208216:web:ee96307b7ee2ed1593b6ed',
    messagingSenderId: '26669208216',
    projectId: 'social-app-71c22',
    authDomain: 'social-app-71c22.firebaseapp.com',
    storageBucket: 'social-app-71c22.appspot.com',
  );
}
